In [2]:
import pandas as pd

### Task 1

In [30]:
from scipy.stats import chi2_contingency


def check_categorical_dependency(data, var1, var2, alpha=0.05):
    contingency_table = pd.crosstab(data[var1], data[var2])

    _, p_value, *_ = chi2_contingency(contingency_table)

    return p_value < alpha

In [34]:
grants_data = pd.read_csv('data/grants.csv')

grants_data.head()

   npersons years_in_uni  oldest_age    field  RFCD.Code.1  midpoint  status
0       2.0          < 5        66.0      bio       270799   24999.5       1
1       1.0          < 5        51.0      bio       270106   24999.5       0
2       1.0          < 5        36.0      bio       270708   24999.5       0
3       1.0         5-10        46.0      bio       270603   24999.5       0
4       4.0         > 10        46.0  physics       240402   24999.5       1

In [33]:
print("Dependency between field and grant status:")
field_result = check_categorical_dependency(grants_data, 'field', 'status')
print("Features are dependent" if field_result else "Features are independent")

Dependency between field and grant status:
Features are independent

In [41]:
grants_data['age_group'] = pd.cut(grants_data['oldest_age'],
                                  bins=[0, 30, 40, 50, 60, 100],
                                  labels=['<30', '30-40', '40-50', '50-60', '>60'])

print("Dependency between age group and grant status:")
age_result = check_categorical_dependency(grants_data, 'age_group', 'status')
print("Features are dependent" if age_result else "Features are independent")

Dependency between age group and grant status:
Features are independent

### Task 2

In [42]:
from scipy.stats import ttest_rel


def check_paired_samples_dependency(data, var1, var2, alpha=0.05):
    _, p_value = ttest_rel(data[var1], data[var2])

    return p_value < alpha

In [43]:
medicine_data = pd.read_csv('data/med.csv')

medicine_data.head()

,Group,Glycemia,Pressure_before,Pressure_after,Cholesterol (April),Cholesterol (March)
0,2,90,170,135,235,205
1,2,85,160,155,185,195
2,1,95,165,155,235,260
3,1,86,170,165,155,136
4,2,104,170,165,260,250

In [44]:
print("Comparing blood pressure before and after treatment:")
result = check_paired_samples_dependency(medicine_data, 'Pressure_before', 'Pressure_after')
print("Features are dependent" if result else "Features are independent")

Comparing blood pressure before and after treatment:
Features are dependent